apiVersion: apps/v1
kind: Deployment
metadata:
  name: myshop-kafka-deployment
  labels:
    name: kafka-service
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      labels:
        app: kafka-service
    spec:
      containers:
        - image: wurstmeister/kafka
          name: kafka-service
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "myshop-kafka-service"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "myshop-zookeeper-service:2181"
