apiVersion: v1
kind: Service
metadata:
  name: myshop-zookeeper-service
spec:
  selector:
    app: zookeeper-service
  ports:
  - name: zookeeper-service
    protocol: TCP
    port: 2181
    targetPort: 2181
