apiVersion: apps/v1
kind: Deployment
metadata:
  name: myshop-admin-deployment
  labels:
    name:  admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - image: nabeelncz/myshop-admin-service:latest
        name: admin-service
        envFrom:
          - configMapRef:
              name: admin-service-config