apiVersion: v1
kind: Service
metadata: 
  name:  myshop-admin-mongodb-service
spec:
  selector:
    app: admin-mongodb
  ports:
  - name:  admin-mongodb
    protocol: TCP
    port:  27017
    targetPort: 27017