apiVersion: apps/v1
kind: Deployment
metadata:
  name: myshop-product-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-mongodb
  template:
    metadata:
      labels:
        app: product-mongodb
    spec:
      containers:
      - name:  product-mongodb
        image: mongo:latest